import { compileTloqueScore } from "@shared/audio"
import type { NativeHybridSource } from "@shared/native-hybrid-source"
import { buildHybridAbReport, type HybridAbMetricId, type HybridAbRegister, type HybridAbRegisterValues } from "@shared/native-hybrid-validation"
import { scheduleHybridPhysicalOverlay } from "./HybridPhysicalOverlay"
import { preferredNativeModuleForInstrument } from "./NativeAutoModule"
import { renderTloqueScoreWithNativeSamplePackToWav } from "./NativeSampleScoreExporter"

export interface HybridAbCalibrationResult { report: ReturnType<typeof buildHybridAbReport>; sampled: Blob; hybrid: Blob }
function clamp01(v:number){return Math.max(0,Math.min(1,v))}
function midiNote(m:number){const n=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];return `${n[((m%12)+12)%12]}${Math.floor(m/12)-1}`}
function registerMidi(source:NativeHybridSource, register:HybridAbRegister){const span=source.midiMax-source.midiMin;const f=register==="low"?.22:register==="mid"?.5:.78;return Math.max(source.midiMin,Math.min(source.midiMax,Math.round(source.midiMin+span*f)))}
function physicalControls(source:NativeHybridSource){
  if(source.physicalLayer==="bowed-string-resonator")return "control 3:1 expression=0.78 brightness=0.68 vibrato=0.10 pressure=0.78 bow=0.25 coupling=0.55 ramp=0.35\ncontrol 4:2 expression=0.42 brightness=0.38 vibrato=0.04 pressure=0.42 bow=0.72 coupling=0.30 ramp=0.35"
  if(source.physicalLayer==="air-column-resonator")return "control 3:1 expression=0.78 brightness=0.68 vibrato=0.10 pressure=0.78 embouchure=0.68 ramp=0.35\ncontrol 4:2 expression=0.42 brightness=0.38 vibrato=0.04 pressure=0.42 embouchure=0.34 ramp=0.35"
  if(source.instrumentId==="piano.grand"||source.instrumentId==="keys.celesta")return "control 3:1 pedal=down damper=0.08 coupling=0.82 expression=0.70 brightness=0.58 ramp=0.15\ncontrol 4:3 pedal=up damper=0.78 coupling=0.32 expression=0.48 brightness=0.46 ramp=0.18"
  return "control 3:1 pluck=0.28 damper=0.12 coupling=0.72 expression=0.70 brightness=0.58 ramp=0.15\ncontrol 4:3 pluck=0.68 damper=0.58 coupling=0.35 expression=0.48 brightness=0.46 ramp=0.18"
}
function block(source:NativeHybridSource, register:HybridAbRegister){const midi=registerMidi(source,register), upper=Math.min(source.midiMax,midi+2), c=physicalControls(source);return `section ${register} form=development bars=5 repeat=1 fade=0 tempo=120 rubato=0\nuse probe\n1:1 ${midiNote(midi)} 2 velocity=0.32 articulation=normal\n2:1 ${midiNote(midi)} 2 velocity=0.84 articulation=normal\n${c}\n3:1 ${midiNote(midi)} 3 velocity=0.62 articulation=normal\n4:1 ${midiNote(upper)} 2 velocity=0.58 articulation=legato\nend`}
function probeScore(source:NativeHybridSource){return `TLOQUE_SCORE 2\ntitle "Hybrid A-B register matrix ${source.instrumentId}"\ntempo 120\nmeter 4/4\nloop false\nseed 20260825\nhumanize 0\nquality studio\nmodule native-auto\ntrack probe synth=pad instrument=${source.instrumentId} program=0 role=melody gain=0.32 pan=0 attack=0.025 release=1 expression=0.55 brightness=0.52 vibrato=0.06\n${block(source,"low")}\n${block(source,"mid")}\n${block(source,"high")}`}
function mono(b:AudioBuffer){const o=new Float32Array(b.length);for(let c=0;c<b.numberOfChannels;c++){const d=b.getChannelData(c);for(let i=0;i<o.length;i++)o[i]+=d[i]/b.numberOfChannels}return o}
function rms(d:Float32Array,s:number,e:number){if(!d.length)return 0;const a=Math.max(0,Math.min(d.length-1,Math.floor(s))),b=Math.max(a+1,Math.min(d.length,Math.floor(e)));let x=0;for(let i=a;i<b;i++)x+=d[i]*d[i];return Math.sqrt(x/Math.max(1,b-a))}
function diffRms(a:Float32Array,b:Float32Array,s:number,e:number){const f=Math.max(0,Math.min(a.length,b.length,Math.floor(s))),t=Math.max(f,Math.min(a.length,b.length,Math.floor(e)));let x=0;if(t<=f)return 0;for(let i=f;i<t;i++){const d=b[i]-a[i];x+=d*d}return Math.sqrt(x/(t-f))}
function cv(d:Float32Array,sr:number,s:number,e:number){const w=Math.max(32,Math.floor(sr*.05)),v:number[]=[];for(let at=Math.floor(s*sr);at+w<=Math.min(d.length,e*sr);at+=w)v.push(rms(d,at,at+w));if(!v.length)return 1;const m=v.reduce((a,b)=>a+b,0)/v.length,q=v.reduce((a,b)=>a+(b-m)**2,0)/v.length;return Math.sqrt(q)/Math.max(1e-6,m)}
function centroid(d:Float32Array,sr:number,sec:number){if(!d.length)return 0;const n=Math.min(512,d.length),center=Math.floor(sec*sr),start=Math.max(0,Math.min(d.length-n,center-n/2));let weighted=0,total=0;for(let k=1;k<n/2;k++){let re=0,im=0;for(let t=0;t<n;t++){const w=.5-.5*Math.cos(2*Math.PI*t/Math.max(1,n-1)),x=(d[start+t]??0)*w,p=2*Math.PI*k*t/n;re+=x*Math.cos(p);im-=x*Math.sin(p)}const mag=Math.hypot(re,im),hz=k*sr/n;total+=mag;weighted+=hz*mag}return weighted/Math.max(1e-9,total)}
function encodeWav(buffer:AudioBuffer){const ch=buffer.numberOfChannels,frames=buffer.length,view=new DataView(new ArrayBuffer(44+frames*ch*2)),txt=(o:number,v:string)=>{for(let i=0;i<v.length;i++)view.setUint8(o+i,v.charCodeAt(i))};txt(0,"RIFF");view.setUint32(4,36+frames*ch*2,true);txt(8,"WAVE");txt(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,ch,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*ch*2,true);view.setUint16(32,ch*2,true);view.setUint16(34,16,true);txt(36,"data");view.setUint32(40,frames*ch*2,true);let o=44;for(let f=0;f<frames;f++)for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[f]));view.setInt16(o,x<0?x*0x8000:x*0x7fff,true);o+=2}return new Blob([view.buffer],{type:"audio/wav"})}
function metricsAt(a:Float32Array,b:Float32Array,sr:number,offset:number):Record<HybridAbMetricId,number>{
  const attacks=[0,2,4,6].map(x=>offset+x);const transient=attacks.reduce((sum,sec)=>{const s=sec*sr,e=(sec+.09)*sr,base=rms(a,s,e);return sum+clamp01(1-diffRms(a,b,s,e)/Math.max(1e-6,base))},0)/attacks.length
  const cvA=cv(a,sr,offset+4.25,offset+5.35),cvB=cv(b,sr,offset+4.25,offset+5.35),continuity=clamp01(.5+(cvA-cvB)/Math.max(.08,cvA+cvB))
  const softA=rms(a,(offset+.2)*sr,(offset+.9)*sr),loudA=rms(a,(offset+2.2)*sr,(offset+2.9)*sr),softB=rms(b,(offset+.2)*sr,(offset+.9)*sr),loudB=rms(b,(offset+2.2)*sr,(offset+2.9)*sr),ca=20*Math.log10(Math.max(1e-6,loudA)/Math.max(1e-6,softA)),cb=20*Math.log10(Math.max(1e-6,loudB)/Math.max(1e-6,softB)),dynamic=clamp01(1-Math.abs(cb-ca)/Math.max(6,Math.abs(ca)))
  const cA=centroid(a,sr,offset+4.8),cB=centroid(b,sr,offset+4.8),spectral=clamp01(Math.abs(cB-cA)/Math.max(1,cA)),active=rms(a,(offset+4.2)*sr,(offset+5.4)*sr),tailA=rms(a,(offset+7.2)*sr,(offset+8.4)*sr),tailB=rms(b,(offset+7.2)*sr,(offset+8.4)*sr),tail=clamp01(Math.max(0,tailB-tailA)/Math.max(1e-6,active)*12)
  return {"transient-preservation":transient,"sustain-continuity":continuity,"dynamic-response":dynamic,"spectral-deviation":spectral,"tail-naturalness":tail}
}
export async function runHybridAbCalibration(source:NativeHybridSource,signal?:AbortSignal):Promise<HybridAbCalibrationResult>{
  const compiled=compileTloqueScore(probeScore(source));if(!compiled.ok||compiled.recipe.version!==2)throw new Error(`No se pudo compilar probe A/B: ${compiled.ok?"versión inválida":compiled.diagnostics.map(x=>x.message).join(" · ")}`);const recipe=compiled.recipe,moduleId=preferredNativeModuleForInstrument(source.instrumentId);if(!moduleId)throw new Error(`No existe sample base para ${source.instrumentId}`)
  const sampled=await renderTloqueScoreWithNativeSamplePackToWav(recipe,"/api/audio/sample-packs/modules/native-auto.json",{quality:"studio",signal,hybridMode:"none"});if(signal?.aborted)throw new DOMException("Calibración cancelada","AbortError")
  const decoder=new OfflineAudioContext(2,1,48_000),sampledBuffer=await decoder.decodeAudioData(await sampled.arrayBuffer()),context=new OfflineAudioContext(sampledBuffer.numberOfChannels,sampledBuffer.length,sampledBuffer.sampleRate),base=context.createBufferSource();base.buffer=sampledBuffer;base.connect(context.destination);base.start(0);const bus=context.createGain();bus.gain.value=.32;bus.connect(context.destination);const track=recipe.plan.tracks[0],controls=recipe.plan.controls;if(!track)throw new Error("Probe A/B sin track");let previousEnd:number|undefined
  for(const event of recipe.plan.events){const legato=event.articulation==="legato"&&previousEnd!==undefined&&event.timeSeconds-previousEnd<=.08;for(const midi of event.notes)scheduleHybridPhysicalOverlay(context,source,{startAt:0,event,track,midi,destination:bus,controls,legatoFromPrevious:legato});previousEnd=event.timeSeconds+event.durationSeconds}
  const hybridBuffer=await context.startRendering(),hybrid=encodeWav(hybridBuffer),a=mono(sampledBuffer),b=mono(hybridBuffer),sr=sampledBuffer.sampleRate
  const registerValues:HybridAbRegisterValues[]=(['low','mid','high'] as const).map((register,index)=>({register,midi:registerMidi(source,register),values:metricsAt(a,b,sr,index*10)}))
  return {report:buildHybridAbReport(source,moduleId,registerValues),sampled,hybrid}
}
