import type { PrintIssue } from "./model"
const es = {
  adjustments: "Ajustes", previewTab: "Maqueta", zoom: "Ampliar maqueta",
  cut: "Continua: recortar", fold: "Discontinua: doblar", glue: "Pegar", kit: "Descargar cubierta recortable PDF",
  kitHint: "Dos hojas verticales, a una cara y al 100 %. Recorta las líneas continuas, dobla las discontinuas y pega la pestaña de la contraportada bajo el lomo. Usa papel compatible con tu impresora.",
  kitConfirm: "Medí el lomo del bloque de páginas y revisaré una prueba.", kitTooWide: "La cubierta con este lomo no cabe en una hoja. Encarga la cubierta a una imprenta.",
  open: "Crear edición física", title: "Taller de ediciones", subtitle: "Del manuscrito al papel", close: "Cerrar taller",
  format: "Formato", design: "Diseño", review: "Revisión", next: "Continuar", back: "Atrás",
  destination: "¿Dónde vas a imprimir?", press: "En una imprenta", pressHint: "Interior a tamaño final y cubierta por separado.",
  home: "En casa", homeHint: "Páginas completas en papel carta o A4.", booklet: "Cuadernillos", bookletHint: "Dos páginas por cara, listas para doblar y encuadernar.",
  trim: "Tamaño del libro", paper: "Papel de la impresora", a5: "A5 · 148 × 210 mm", trade: "Novela · 152.4 × 228.6 mm", digest: "Media carta · 139.7 × 215.9 mm",
  letter: "Carta · 215.9 × 279.4 mm", a4: "A4 · 210 × 297 mm", signature: "Páginas por cuadernillo",
  signatureHint: "Cada cuadernillo se dobla por separado y se reúne en orden. Prueba primero uno con tu papel.",
  style: "Dirección editorial", classic: "Literaria", classicHint: "Sangrías y composición clásica.", contemporary: "Contemporánea", contemporaryHint: "Párrafos abiertos y ritmo ligero.", large: "Lectura amplia", largeHint: "Letra de 15 pt y más interlineado.",
  type: "Tipografía", typeHint: "Source Serif 4 · incluida en el PDF", size: "Cuerpo · pt", leading: "Interlineado", margins: "Márgenes · mm", inner: "Interior", outer: "Exterior", top: "Superior", bottom: "Inferior",
  structure: "Estructura", recto: "Capítulos en página derecha", toc: "Índice con páginas", headers: "Encabezados de lectura", justify: "Justificado moderado",
  textMode: "Saltos del manuscrito", paragraphs: "Un párrafo por salto de línea", reflow: "Prosa: unir líneas entre renglones vacíos", verse: "Verso: conservar líneas y estrofas",
  textHint: "Elige cómo interpretar los saltos existentes. La opción de prosa ayuda con textos de Gutenberg cortados en renglones.",
  preview: "Maqueta paginada", interior: "Interior", cover: "Cubierta", guides: "Mostrar guías", previousPage: "Página anterior", nextPage: "Página siguiente", page: "Página", of: "de", chapter: "Ir al capítulo", titlePage: "Portadilla", blanks: "Páginas en blanco",
  composing: "Componiendo la edición…", composingHint: "Calculando el índice, los saltos y los márgenes de cada página.", pages: "páginas", sheets: "hojas", signatures: "cuadernillos", words: "palabras",
  coverSettings: "Preparar la cubierta", spine: "Lomo confirmado · mm", spineHint: "Pide el ancho a tu imprenta para este número de páginas, papel y encuadernación. Debe recalcularse si cambia la edición.", bleed: "Sangrado · mm",
  artwork: "Incluir ilustración de portada", blurb: "Texto de contraportada", blurbHint: "Ajusta este texto para la edición impresa. El libro original conserva su sinopsis.",
  preflight: "Antes de imprimir", ready: "Interior comprobado", warnings: "Puntos para revisar", blocked: "Hay un problema que resolver", export: "Descargar interior PDF", exportBooklet: "Descargar cuadernillos PDF", exportCover: "Descargar cubierta PDF", exportReport: "Descargar ficha de impresión", exporting: "Preparando archivo…",
  pressInstructions: "Entrega el interior en páginas individuales y la cubierta en un archivo separado. Confirma tamaños, papel y encuadernación con tu imprenta; revisa una prueba física antes de la tirada.",
  homeInstructions: "Imprime a tamaño real (100 %), una página por cara y doble cara por el borde largo. Desactiva «Ajustar a página». Haz una prueba de dos hojas para comprobar orientación y márgenes.",
  bookletInstructions: "Usa papel apaisado, tamaño real (100 %) y doble cara por el borde corto. El PDF ya está ordenado: no actives «Folleto» ni «2 páginas por hoja» en la impresora. Prueba primero un cuadernillo.",
  plan: "Orden de las hojas", group: "Cuadernillo", sheet: "Hoja", side: "Cara", front: "Frente", backSide: "Reverso", left: "Izquierda", right: "Derecha",
  coverConfirm: "La imprenta revisará el color y su plantilla de cubierta.",
  pdfLimit: "PDF con fuentes incrustadas; sin certificación PDF/X ni perfil de salida ICC. Las guías solo aparecen en la maqueta.",
  copyHint: "Este archivo conserva el folio del ejemplar. La clave de activación aparece únicamente en el interior.",
  genericHint: "Preparar un PDF no crea un folio ni amplía los permisos de impresión o venta de la obra.",
  error: "No se pudo preparar la edición. Reintenta o reduce el tamaño del manuscrito.", fontsError: "No se pudieron cargar las fuentes. Comprueba la conexión y reintenta.",
  retry: "Reintentar", reset: "Restablecer diseño", saved: "Diseño guardado en este dispositivo", fullTextError: "No encontramos el texto completo. Abre el libro o descárgalo de nuevo antes de imprimir.",
  original: "La cubierta se adapta sin deformar la ilustración.", ppi: "Resolución efectiva", noCover: "Cubierta tipográfica", settingsChanged: "Revisión actualizada al diseño seleccionado.",
}
type Key = keyof typeof es
const en: Record<Key, string> = {
  adjustments: "Settings", previewTab: "Preview", zoom: "Enlarge preview",
  cut: "Solid: cut", fold: "Dashed: fold", glue: "Glue", kit: "Download cut-out cover PDF",
  kitHint: "Two portrait sheets, single-sided, at 100%. Cut solid lines, fold dashed lines and glue the back-cover tab under the spine. Use paper your printer supports.",
  kitConfirm: "I measured the page block's spine and will check a proof.", kitTooWide: "The cover and spine do not fit on one sheet. Have a print shop make the cover.",
  open: "Create print edition", title: "Edition studio", subtitle: "From manuscript to paper", close: "Close studio",
  format: "Format", design: "Design", review: "Review", next: "Continue", back: "Back",
  destination: "Where will you print?", press: "Print shop", pressHint: "Final-size interior and a separate cover file.", home: "At home", homeHint: "Full pages on Letter or A4 paper.", booklet: "Booklets", bookletHint: "Two pages per side, ready to fold and bind.",
  trim: "Book size", paper: "Printer paper", a5: "A5 · 148 × 210 mm", trade: "Trade · 152.4 × 228.6 mm", digest: "Digest · 139.7 × 215.9 mm", letter: "Letter · 215.9 × 279.4 mm", a4: "A4 · 210 × 297 mm",
  signature: "Pages per signature", signatureHint: "Fold each signature separately and gather in order. Test one with your paper first.",
  style: "Editorial style", classic: "Literary", classicHint: "Indents and classic composition.", contemporary: "Contemporary", contemporaryHint: "Open paragraphs and generous spacing.", large: "Large print", largeHint: "15 pt type with extra leading.",
  type: "Typography", typeHint: "Source Serif 4 · embedded in the PDF", size: "Type size · pt", leading: "Line spacing", margins: "Margins · mm", inner: "Inside", outer: "Outside", top: "Top", bottom: "Bottom",
  structure: "Structure", recto: "Start chapters on right pages", toc: "Contents with page numbers", headers: "Running headers", justify: "Moderate justification",
  textMode: "Manuscript line breaks", paragraphs: "One paragraph per line break", reflow: "Prose: join lines between blank lines", verse: "Verse: preserve lines and stanzas", textHint: "Choose how to interpret existing breaks. Prose mode helps with Gutenberg texts wrapped into short lines.",
  preview: "Paginated layout", interior: "Interior", cover: "Cover", guides: "Show guides", previousPage: "Previous page", nextPage: "Next page", page: "Page", of: "of", chapter: "Go to chapter", titlePage: "Title page", blanks: "Blank pages",
  composing: "Composing your edition…", composingHint: "Calculating contents, page breaks and margins.", pages: "pages", sheets: "sheets", signatures: "signatures", words: "words",
  coverSettings: "Prepare the cover", spine: "Confirmed spine · mm", spineHint: "Ask your printer for the width for this page count, paper and binding. Recalculate it whenever the edition changes.", bleed: "Bleed · mm", artwork: "Include cover artwork", blurb: "Back cover text", blurbHint: "Adjust this text for print. The book's original synopsis is unchanged.",
  preflight: "Before printing", ready: "Interior checked", warnings: "Items to review", blocked: "An issue needs attention", export: "Download interior PDF", exportBooklet: "Download booklet PDF", exportCover: "Download cover PDF", exportReport: "Download print job sheet", exporting: "Preparing file…",
  pressInstructions: "Send the interior as single pages and the cover as a separate file. Confirm sizes, paper and binding with your printer; approve a physical proof before the print run.",
  homeInstructions: "Print at actual size (100%), one page per side, duplex on the long edge. Turn off ‘Fit to page’. Test two sheets to check orientation and margins.",
  bookletInstructions: "Use landscape paper, actual size (100%) and short-edge duplex. This PDF is already imposed: do not enable ‘Booklet’ or ‘2 pages per sheet’ in your printer. Test one signature first.",
  plan: "Sheet order", group: "Signature", sheet: "Sheet", side: "Side", front: "Front", backSide: "Back", left: "Left", right: "Right",
  coverConfirm: "The printer will review color and its cover template.", pdfLimit: "PDF with embedded fonts; no PDF/X certification or ICC output profile. Guides appear only in the preview.", copyHint: "This file keeps the copy's folio. The activation key appears only inside the book.", genericHint: "Creating a PDF does not issue a folio or extend printing or sales permissions.",
  error: "The edition could not be prepared. Retry or reduce the manuscript size.", fontsError: "Fonts could not be loaded. Check your connection and retry.", retry: "Retry", reset: "Reset design", saved: "Design saved on this device", fullTextError: "The complete text was not found. Open or download the book again before printing.",
  original: "The cover fits the artwork without distorting it.", ppi: "Effective resolution", noCover: "Typographic cover", settingsChanged: "Review updated to the selected design.",
}
export const printText = (language: string) => (key: Key) => (language.startsWith("es") ? es : en)[key]
export function issueText(language: string, issue: PrintIssue): string {
  const spanish = language.startsWith("es")
  const messages: Record<PrintIssue["code"], [string, string]> = {
    missingText: ["Falta el texto completo del libro.", "The complete book text is missing."],
    tooLong: ["Esta edición supera 6 millones de caracteres o 1800 páginas. Divídela en volúmenes.", "This edition exceeds 6 million characters or 1800 pages. Split it into volumes."],
    missingGlyph: ["La fuente no cubre todos los caracteres. No se exportará texto incompleto.", "The font does not cover every character. Incomplete text will not be exported."],
    unsupportedScript: ["Esta escritura necesita un motor de composición adicional. El taller actual admite texto latino, griego y cirílico.", "This script needs an additional shaping engine. This studio currently supports Latin, Greek and Cyrillic text."],
    gutter: ["Aumenta el margen interior para este número de páginas. Referencia mínima en mm:", "Increase the inside margin for this page count. Reference minimum in mm:"],
    coverMissing: ["No se pudo cargar la imagen; la cubierta usa el diseño tipográfico.", "The image could not be loaded; the cover uses the typographic design."],
    coverResolution: ["La ilustración queda por debajo de 300 ppp al tamaño de impresión. Resolución actual:", "Artwork is below 300 ppi at print size. Current resolution:"],
    spineRequired: ["Indica el ancho de lomo confirmado para exportar la cubierta.", "Enter the confirmed spine width to export the cover."],
    colorProfile: ["Confirma el perfil de color y la plantilla de tu imprenta. Esta cubierta no está certificada como PDF/X.", "Confirm the printer's color profile and template. This cover is not PDF/X certified."],
    longWord: ["Se ha partido una palabra muy larga. Revisa el salto en la página indicada.", "A very long word was split. Review the break on the indicated page."],
    coverOverflow: ["El texto de cubierta no cabe. Reduce la contraportada o revisa el título antes de exportar.", "Cover text overflows. Shorten the blurb or review the title before exporting."],
  }
  return messages[issue.code][spanish ? 0 : 1] + (issue.detail ? " " + issue.detail : "") + (issue.page ? " (" + (spanish ? "pág." : "p.") + " " + issue.page + ")" : "")
}
