export const EXPERIENCE_LANGUAGES = ["es", "en", "fr", "de", "it", "pt", "ja", "zh", "ar"] as const
export type ExperienceLanguage = typeof EXPERIENCE_LANGUAGES[number]

const es = {
  home: "Inicio", studio: "Estudio", inbox: "Buzón", profile: "Perfil", admin: "Administración",
  library: "Biblioteca", editions: "Ediciones", notifications: "Notificaciones", messages: "Mensajes",
  unread: "sin leer", markAllRead: "Marcar todo como leído", emptyInbox: "No tienes avisos pendientes.",
  transactionalInbox: "Aquí llegan reclamos de ejemplares y avisos importantes de tus obras.",
  directMessagesProtected: "Los mensajes directos se abrirán cuando estén listos bloquear, silenciar, reportar y moderar.",
  reader: "Lector", author: "Autor", administrator: "Administrador", accountMode: "Tu espacio",
  completeProfile: "Completa tu presencia", profileComplete: "Perfil completo", profileHint: "Un perfil claro ayuda a que tus lectores te reconozcan sin obligarte a publicar.",
  editProfile: "Editar perfil", startWriting: "Empezar a escribir", manageEditions: "Gestionar ediciones",
  adminCenter: "Centro de administración", adminCenterHint: "Herramientas operativas separadas de la experiencia de lectura.",
  catalog: "Catálogo y Gutenberg", phonotheque: "Fonoteca", frames: "Marcos", diagnostics: "Diagnóstico visual", admins: "Administradores",
  adminOverlay: "Controles administrativos en catálogo", adminOverlayHint: "Actívalos solo mientras moderas obras.",
  addAdmin: "Agregar administrador", founder: "Fundador", remove: "Quitar", noAccess: "Esta zona es solo para administradores.",
  commercialCopies: "Ejemplares comerciales", commercialHint: "Venta física y reclamo digital son estados independientes.",
  total: "Total", available: "Disponible", sold: "Vendido", returned: "Devuelto", digitalClaimed: "Digital reclamado", digitalPending: "Digital sin reclamar",
  markSold: "Marcar vendido", markAvailable: "Volver a disponible", markReturned: "Marcar devolución", price: "Precio", channel: "Canal", note: "Nota", save: "Guardar", cancel: "Cancelar",
  noEditions: "Aún no tienes ejemplares con permiso de venta.", copyClaimed: "Se reclamó un ejemplar", copyClaimedBody: "El folio {folio} ya tiene acceso digital.",
} as const

export type ExperienceKey = keyof typeof es

const en: Record<ExperienceKey, string> = {
  home:"Home",studio:"Studio",inbox:"Inbox",profile:"Profile",admin:"Admin",library:"Library",editions:"Editions",notifications:"Notifications",messages:"Messages",unread:"unread",markAllRead:"Mark all as read",emptyInbox:"You have no pending notices.",transactionalInbox:"Claims and important notices about your works arrive here.",directMessagesProtected:"Direct messages will open when block, mute, report, and moderation are ready.",reader:"Reader",author:"Author",administrator:"Administrator",accountMode:"Your space",completeProfile:"Complete your presence",profileComplete:"Profile complete",profileHint:"A clear profile helps readers recognize you without requiring you to publish.",editProfile:"Edit profile",startWriting:"Start writing",manageEditions:"Manage editions",adminCenter:"Admin center",adminCenterHint:"Operational tools kept separate from the reading experience.",catalog:"Catalog and Gutenberg",phonotheque:"Music library",frames:"Frames",diagnostics:"Visual diagnostics",admins:"Administrators",adminOverlay:"Admin controls in catalog",adminOverlayHint:"Enable only while moderating works.",addAdmin:"Add administrator",founder:"Founder",remove:"Remove",noAccess:"This area is for administrators only.",commercialCopies:"Commercial copies",commercialHint:"Physical sale and digital claim are independent states.",total:"Total",available:"Available",sold:"Sold",returned:"Returned",digitalClaimed:"Digital claimed",digitalPending:"Digital unclaimed",markSold:"Mark sold",markAvailable:"Make available",markReturned:"Mark returned",price:"Price",channel:"Channel",note:"Note",save:"Save",cancel:"Cancel",noEditions:"You do not have sale-permitted copies yet.",copyClaimed:"A copy was claimed",copyClaimedBody:"Folio {folio} now has digital access.",
}
const fr: Record<ExperienceKey, string> = {
  home:"Accueil",studio:"Studio",inbox:"Boîte",profile:"Profil",admin:"Administration",library:"Bibliothèque",editions:"Éditions",notifications:"Notifications",messages:"Messages",unread:"non lues",markAllRead:"Tout marquer comme lu",emptyInbox:"Aucun avis en attente.",transactionalInbox:"Les réclamations et avis importants sur vos œuvres arrivent ici.",directMessagesProtected:"Les messages directs ouvriront avec blocage, sourdine, signalement et modération.",reader:"Lecteur",author:"Auteur",administrator:"Administrateur",accountMode:"Votre espace",completeProfile:"Complétez votre présence",profileComplete:"Profil complet",profileHint:"Un profil clair aide les lecteurs à vous reconnaître sans devoir publier.",editProfile:"Modifier le profil",startWriting:"Commencer à écrire",manageEditions:"Gérer les éditions",adminCenter:"Centre d’administration",adminCenterHint:"Outils opérationnels séparés de la lecture.",catalog:"Catalogue et Gutenberg",phonotheque:"Phonothèque",frames:"Cadres",diagnostics:"Diagnostic visuel",admins:"Administrateurs",adminOverlay:"Contrôles admin du catalogue",adminOverlayHint:"Activez-les uniquement pendant la modération.",addAdmin:"Ajouter un administrateur",founder:"Fondateur",remove:"Retirer",noAccess:"Cette zone est réservée aux administrateurs.",commercialCopies:"Exemplaires commerciaux",commercialHint:"Vente physique et réclamation numérique sont indépendantes.",total:"Total",available:"Disponible",sold:"Vendu",returned:"Retourné",digitalClaimed:"Numérique réclamé",digitalPending:"Numérique non réclamé",markSold:"Marquer vendu",markAvailable:"Rendre disponible",markReturned:"Marquer retourné",price:"Prix",channel:"Canal",note:"Note",save:"Enregistrer",cancel:"Annuler",noEditions:"Vous n’avez pas encore d’exemplaires autorisés à la vente.",copyClaimed:"Un exemplaire a été réclamé",copyClaimedBody:"Le folio {folio} a désormais un accès numérique.",
}
const de: Record<ExperienceKey, string> = {
  home:"Start",studio:"Studio",inbox:"Postfach",profile:"Profil",admin:"Verwaltung",library:"Bibliothek",editions:"Ausgaben",notifications:"Mitteilungen",messages:"Nachrichten",unread:"ungelesen",markAllRead:"Alle als gelesen markieren",emptyInbox:"Keine offenen Hinweise.",transactionalInbox:"Ansprüche und wichtige Hinweise zu deinen Werken erscheinen hier.",directMessagesProtected:"Direktnachrichten starten erst mit Blockieren, Stummschalten, Melden und Moderation.",reader:"Leser",author:"Autor",administrator:"Administrator",accountMode:"Dein Bereich",completeProfile:"Präsenz vervollständigen",profileComplete:"Profil vollständig",profileHint:"Ein klares Profil macht dich erkennbar, ohne eine Veröffentlichung zu verlangen.",editProfile:"Profil bearbeiten",startWriting:"Schreiben beginnen",manageEditions:"Ausgaben verwalten",adminCenter:"Verwaltungszentrum",adminCenterHint:"Betriebswerkzeuge getrennt vom Lesen.",catalog:"Katalog und Gutenberg",phonotheque:"Musikarchiv",frames:"Rahmen",diagnostics:"Visuelle Diagnose",admins:"Administratoren",adminOverlay:"Admin-Steuerung im Katalog",adminOverlayHint:"Nur während der Moderation aktivieren.",addAdmin:"Administrator hinzufügen",founder:"Gründer",remove:"Entfernen",noAccess:"Dieser Bereich ist nur für Administratoren.",commercialCopies:"Kommerzielle Exemplare",commercialHint:"Physischer Verkauf und digitaler Anspruch sind getrennt.",total:"Gesamt",available:"Verfügbar",sold:"Verkauft",returned:"Zurückgegeben",digitalClaimed:"Digital beansprucht",digitalPending:"Digital offen",markSold:"Als verkauft markieren",markAvailable:"Verfügbar machen",markReturned:"Rückgabe markieren",price:"Preis",channel:"Kanal",note:"Notiz",save:"Speichern",cancel:"Abbrechen",noEditions:"Noch keine Exemplare mit Verkaufserlaubnis.",copyClaimed:"Exemplar beansprucht",copyClaimedBody:"Folio {folio} hat jetzt digitalen Zugang.",
}
const it: Record<ExperienceKey, string> = {
  home:"Home",studio:"Studio",inbox:"Posta",profile:"Profilo",admin:"Amministrazione",library:"Biblioteca",editions:"Edizioni",notifications:"Notifiche",messages:"Messaggi",unread:"non lette",markAllRead:"Segna tutto come letto",emptyInbox:"Nessun avviso in sospeso.",transactionalInbox:"Qui arrivano riscatti e avvisi importanti sulle tue opere.",directMessagesProtected:"I messaggi diretti apriranno con blocco, silenzio, segnalazione e moderazione.",reader:"Lettore",author:"Autore",administrator:"Amministratore",accountMode:"Il tuo spazio",completeProfile:"Completa la tua presenza",profileComplete:"Profilo completo",profileHint:"Un profilo chiaro aiuta i lettori a riconoscerti senza obbligarti a pubblicare.",editProfile:"Modifica profilo",startWriting:"Inizia a scrivere",manageEditions:"Gestisci edizioni",adminCenter:"Centro amministrativo",adminCenterHint:"Strumenti operativi separati dalla lettura.",catalog:"Catalogo e Gutenberg",phonotheque:"Fonoteca",frames:"Cornici",diagnostics:"Diagnostica visiva",admins:"Amministratori",adminOverlay:"Controlli admin nel catalogo",adminOverlayHint:"Attivali solo durante la moderazione.",addAdmin:"Aggiungi amministratore",founder:"Fondatore",remove:"Rimuovi",noAccess:"Area riservata agli amministratori.",commercialCopies:"Copie commerciali",commercialHint:"Vendita fisica e riscatto digitale sono stati indipendenti.",total:"Totale",available:"Disponibile",sold:"Venduto",returned:"Reso",digitalClaimed:"Digitale riscattato",digitalPending:"Digitale non riscattato",markSold:"Segna venduto",markAvailable:"Rendi disponibile",markReturned:"Segna reso",price:"Prezzo",channel:"Canale",note:"Nota",save:"Salva",cancel:"Annulla",noEditions:"Non hai ancora copie autorizzate alla vendita.",copyClaimed:"Una copia è stata riscattata",copyClaimedBody:"Il folio {folio} ora ha accesso digitale.",
}
const pt: Record<ExperienceKey, string> = {
  home:"Início",studio:"Estúdio",inbox:"Caixa",profile:"Perfil",admin:"Administração",library:"Biblioteca",editions:"Edições",notifications:"Notificações",messages:"Mensagens",unread:"não lidas",markAllRead:"Marcar tudo como lido",emptyInbox:"Nenhum aviso pendente.",transactionalInbox:"Resgates e avisos importantes sobre tuas obras chegam aqui.",directMessagesProtected:"Mensagens diretas abrirão com bloquear, silenciar, denunciar e moderar.",reader:"Leitor",author:"Autor",administrator:"Administrador",accountMode:"Teu espaço",completeProfile:"Completa tua presença",profileComplete:"Perfil completo",profileHint:"Um perfil claro ajuda leitores a reconhecer-te sem exigir publicação.",editProfile:"Editar perfil",startWriting:"Começar a escrever",manageEditions:"Gerir edições",adminCenter:"Centro administrativo",adminCenterHint:"Ferramentas operacionais separadas da leitura.",catalog:"Catálogo e Gutenberg",phonotheque:"Fonoteca",frames:"Molduras",diagnostics:"Diagnóstico visual",admins:"Administradores",adminOverlay:"Controlos admin no catálogo",adminOverlayHint:"Ativa apenas durante a moderação.",addAdmin:"Adicionar administrador",founder:"Fundador",remove:"Remover",noAccess:"Área exclusiva para administradores.",commercialCopies:"Exemplares comerciais",commercialHint:"Venda física e resgate digital são estados independentes.",total:"Total",available:"Disponível",sold:"Vendido",returned:"Devolvido",digitalClaimed:"Digital resgatado",digitalPending:"Digital não resgatado",markSold:"Marcar vendido",markAvailable:"Tornar disponível",markReturned:"Marcar devolução",price:"Preço",channel:"Canal",note:"Nota",save:"Guardar",cancel:"Cancelar",noEditions:"Ainda não tens exemplares autorizados para venda.",copyClaimed:"Um exemplar foi resgatado",copyClaimedBody:"O fólio {folio} agora tem acesso digital.",
}
const ja: Record<ExperienceKey, string> = {
  home:"ホーム",studio:"スタジオ",inbox:"受信箱",profile:"プロフィール",admin:"管理",library:"ライブラリ",editions:"版管理",notifications:"通知",messages:"メッセージ",unread:"未読",markAllRead:"すべて既読",emptyInbox:"未処理のお知らせはありません。",transactionalInbox:"作品の受取や重要なお知らせが届きます。",directMessagesProtected:"ブロック・ミュート・報告・モデレーションの準備後にDMを開放します。",reader:"読者",author:"著者",administrator:"管理者",accountMode:"あなたの空間",completeProfile:"プロフィールを完成",profileComplete:"プロフィール完成",profileHint:"明確なプロフィールは、公開を強制せず読者にあなたを伝えます。",editProfile:"プロフィール編集",startWriting:"執筆を始める",manageEditions:"版を管理",adminCenter:"管理センター",adminCenterHint:"読書体験から分離した運用ツールです。",catalog:"カタログとGutenberg",phonotheque:"音楽カタログ",frames:"フレーム",diagnostics:"表示診断",admins:"管理者",adminOverlay:"カタログ管理操作",adminOverlayHint:"モデレーション時のみ有効にしてください。",addAdmin:"管理者を追加",founder:"創設者",remove:"削除",noAccess:"管理者専用エリアです。",commercialCopies:"販売用の本",commercialHint:"実物販売とデジタル受取は別の状態です。",total:"合計",available:"販売可能",sold:"販売済み",returned:"返品",digitalClaimed:"デジタル受取済み",digitalPending:"デジタル未受取",markSold:"販売済みにする",markAvailable:"販売可能に戻す",markReturned:"返品にする",price:"価格",channel:"販売先",note:"メモ",save:"保存",cancel:"キャンセル",noEditions:"販売許可付きの本はまだありません。",copyClaimed:"本が受け取られました",copyClaimedBody:"フォリオ {folio} にデジタルアクセスが付きました。",
}
const zh: Record<ExperienceKey, string> = {
  home:"首页",studio:"创作室",inbox:"收件箱",profile:"个人资料",admin:"管理",library:"书库",editions:"版本",notifications:"通知",messages:"消息",unread:"未读",markAllRead:"全部标为已读",emptyInbox:"没有待处理通知。",transactionalInbox:"作品副本领取和重要通知会显示在这里。",directMessagesProtected:"私信将在屏蔽、静音、举报和审核功能就绪后开放。",reader:"读者",author:"作者",administrator:"管理员",accountMode:"你的空间",completeProfile:"完善个人形象",profileComplete:"资料已完整",profileHint:"清晰的资料能帮助读者认识你，并不要求先发布作品。",editProfile:"编辑资料",startWriting:"开始写作",manageEditions:"管理版本",adminCenter:"管理中心",adminCenterHint:"运营工具与阅读体验分开。",catalog:"目录与Gutenberg",phonotheque:"音乐库",frames:"边框",diagnostics:"视觉诊断",admins:"管理员",adminOverlay:"目录管理控件",adminOverlayHint:"仅在审核作品时启用。",addAdmin:"添加管理员",founder:"创始人",remove:"移除",noAccess:"此区域仅限管理员。",commercialCopies:"商业副本",commercialHint:"实体销售与数字领取是独立状态。",total:"总计",available:"可售",sold:"已售",returned:"已退",digitalClaimed:"数字版已领取",digitalPending:"数字版未领取",markSold:"标为已售",markAvailable:"恢复可售",markReturned:"标为退货",price:"价格",channel:"渠道",note:"备注",save:"保存",cancel:"取消",noEditions:"你还没有获准销售的副本。",copyClaimed:"一个副本已领取",copyClaimedBody:"编号 {folio} 现已获得数字访问权。",
}
const ar: Record<ExperienceKey, string> = {
  home:"الرئيسية",studio:"الاستوديو",inbox:"الوارد",profile:"الملف",admin:"الإدارة",library:"المكتبة",editions:"الطبعات",notifications:"الإشعارات",messages:"الرسائل",unread:"غير مقروء",markAllRead:"تحديد الكل كمقروء",emptyInbox:"لا توجد تنبيهات معلقة.",transactionalInbox:"تصل هنا مطالبات النسخ والتنبيهات المهمة حول أعمالك.",directMessagesProtected:"ستفتح الرسائل المباشرة بعد تجهيز الحظر والكتم والإبلاغ والإشراف.",reader:"قارئ",author:"مؤلف",administrator:"مشرف",accountMode:"مساحتك",completeProfile:"أكمل حضورك",profileComplete:"الملف مكتمل",profileHint:"يساعد الملف الواضح القراء على التعرف إليك دون إلزامك بالنشر.",editProfile:"تعديل الملف",startWriting:"ابدأ الكتابة",manageEditions:"إدارة الطبعات",adminCenter:"مركز الإدارة",adminCenterHint:"أدوات تشغيل منفصلة عن تجربة القراءة.",catalog:"الفهرس وGutenberg",phonotheque:"مكتبة الموسيقى",frames:"الإطارات",diagnostics:"فحص العرض",admins:"المشرفون",adminOverlay:"أدوات الإدارة في الفهرس",adminOverlayHint:"فعّلها فقط أثناء الإشراف.",addAdmin:"إضافة مشرف",founder:"المؤسس",remove:"إزالة",noAccess:"هذه المنطقة للمشرفين فقط.",commercialCopies:"النسخ التجارية",commercialHint:"البيع الورقي والمطالبة الرقمية حالتان مستقلتان.",total:"الإجمالي",available:"متاح",sold:"مباع",returned:"مُعاد",digitalClaimed:"تمت المطالبة الرقمية",digitalPending:"لم تتم المطالبة الرقمية",markSold:"تحديد كمباع",markAvailable:"إعادته متاحًا",markReturned:"تحديد كإعادة",price:"السعر",channel:"القناة",note:"ملاحظة",save:"حفظ",cancel:"إلغاء",noEditions:"لا توجد لديك نسخ مرخصة للبيع بعد.",copyClaimed:"تمت المطالبة بنسخة",copyClaimedBody:"أصبح للفوليو {folio} وصول رقمي.",
}

export const EXPERIENCE_STRINGS: Record<ExperienceLanguage, Record<ExperienceKey, string>> = { es, en, fr, de, it, pt, ja, zh, ar }

export function experienceText(language: string, key: ExperienceKey, vars?: Record<string, string | number>): string {
  const lang = EXPERIENCE_LANGUAGES.includes(language as ExperienceLanguage) ? language as ExperienceLanguage : "es"
  let value = EXPERIENCE_STRINGS[lang][key]
  for (const [name, replacement] of Object.entries(vars || {})) value = value.replace(`{${name}}`, String(replacement))
  return value
}
