export const NARRATIVE_UI_LANGUAGES = ["es", "en", "fr", "de", "it", "pt", "ja", "zh", "ar"] as const
export type NarrativeUiLanguage = typeof NARRATIVE_UI_LANGUAGES[number]

export const NARRATIVE_UI_STRINGS = {
  es: { title: "Dirección musical", subtitle: "Anotaciones invisibles para una música que acompaña", hidden: "No modifica el manuscrito", oracle: "Dirigir capítulo con Oráculo", analyzing: "Oráculo está leyendo…", subscription: "Disponible con suscripción Estética o Audio", unavailable: "Oráculo aún no está configurado", paper: "Papel", regions: "regiones", noRegions: "Aún no hay regiones musicales", addRegion: "Añadir región manual", save: "Guardar dirección", compile: "Probar perfil", publish: "Publicar experiencia", saved: "Dirección guardada", compiled: "Perfil listo para revisar", published: "Experiencia publicada", accept: "Pasar al editor", discard: "Descartar", proposal: "Propuesta de Oráculo", paragraph: "Párrafos", intensity: "Intensidad", confidence: "Confianza", remove: "Eliminar", close: "Cerrar", stale: "Guarda el capítulo antes de analizarlo", error: "No se pudo completar la acción" },
  en: { title: "Music direction", subtitle: "Invisible notes for music that accompanies the reader", hidden: "Does not alter the manuscript", oracle: "Direct chapter with Oracle", analyzing: "Oracle is reading…", subscription: "Available with Aesthetic or Audio subscription", unavailable: "Oracle is not configured yet", paper: "Paper", regions: "regions", noRegions: "No music regions yet", addRegion: "Add manual region", save: "Save direction", compile: "Test profile", publish: "Publish experience", saved: "Direction saved", compiled: "Profile ready for review", published: "Experience published", accept: "Move to editor", discard: "Discard", proposal: "Oracle proposal", paragraph: "Paragraphs", intensity: "Intensity", confidence: "Confidence", remove: "Remove", close: "Close", stale: "Save the chapter before analyzing it", error: "The action could not be completed" },
  fr: { title: "Direction musicale", subtitle: "Annotations invisibles pour une musique d’accompagnement", hidden: "Ne modifie pas le manuscrit", oracle: "Diriger le chapitre avec Oracle", analyzing: "Oracle lit…", subscription: "Disponible avec l’abonnement Esthétique ou Audio", unavailable: "Oracle n’est pas encore configuré", paper: "Papier", regions: "régions", noRegions: "Aucune région musicale", addRegion: "Ajouter une région manuelle", save: "Enregistrer la direction", compile: "Tester le profil", publish: "Publier l’expérience", saved: "Direction enregistrée", compiled: "Profil prêt à vérifier", published: "Expérience publiée", accept: "Passer dans l’éditeur", discard: "Ignorer", proposal: "Proposition d’Oracle", paragraph: "Paragraphes", intensity: "Intensité", confidence: "Confiance", remove: "Supprimer", close: "Fermer", stale: "Enregistrez le chapitre avant l’analyse", error: "L’action n’a pas pu aboutir" },
  de: { title: "Musikregie", subtitle: "Unsichtbare Notizen für begleitende Musik", hidden: "Ändert das Manuskript nicht", oracle: "Kapitel mit Oracle inszenieren", analyzing: "Oracle liest…", subscription: "Mit Ästhetik- oder Audio-Abo verfügbar", unavailable: "Oracle ist noch nicht eingerichtet", paper: "Papier", regions: "Regionen", noRegions: "Noch keine Musikregionen", addRegion: "Manuelle Region hinzufügen", save: "Regie speichern", compile: "Profil testen", publish: "Erlebnis veröffentlichen", saved: "Regie gespeichert", compiled: "Profil bereit zur Prüfung", published: "Erlebnis veröffentlicht", accept: "In den Editor übernehmen", discard: "Verwerfen", proposal: "Oracle-Vorschlag", paragraph: "Absätze", intensity: "Intensität", confidence: "Sicherheit", remove: "Entfernen", close: "Schließen", stale: "Kapitel vor der Analyse speichern", error: "Aktion konnte nicht abgeschlossen werden" },
  it: { title: "Direzione musicale", subtitle: "Annotazioni invisibili per una musica di accompagnamento", hidden: "Non modifica il manoscritto", oracle: "Dirigi il capitolo con Oracle", analyzing: "Oracle sta leggendo…", subscription: "Disponibile con abbonamento Estetica o Audio", unavailable: "Oracle non è ancora configurato", paper: "Carta", regions: "regioni", noRegions: "Nessuna regione musicale", addRegion: "Aggiungi regione manuale", save: "Salva direzione", compile: "Prova profilo", publish: "Pubblica esperienza", saved: "Direzione salvata", compiled: "Profilo pronto da verificare", published: "Esperienza pubblicata", accept: "Porta nell’editor", discard: "Scarta", proposal: "Proposta di Oracle", paragraph: "Paragrafi", intensity: "Intensità", confidence: "Affidabilità", remove: "Elimina", close: "Chiudi", stale: "Salva il capitolo prima dell’analisi", error: "Impossibile completare l’azione" },
  pt: { title: "Direção musical", subtitle: "Anotações invisíveis para uma música que acompanha", hidden: "Não altera o manuscrito", oracle: "Dirigir capítulo com Oráculo", analyzing: "Oráculo está lendo…", subscription: "Disponível com assinatura Estética ou Áudio", unavailable: "Oráculo ainda não está configurado", paper: "Papel", regions: "regiões", noRegions: "Ainda não há regiões musicais", addRegion: "Adicionar região manual", save: "Salvar direção", compile: "Testar perfil", publish: "Publicar experiência", saved: "Direção salva", compiled: "Perfil pronto para revisão", published: "Experiência publicada", accept: "Levar ao editor", discard: "Descartar", proposal: "Proposta do Oráculo", paragraph: "Parágrafos", intensity: "Intensidade", confidence: "Confiança", remove: "Excluir", close: "Fechar", stale: "Salve o capítulo antes de analisá-lo", error: "Não foi possível concluir a ação" },
  ja: { title: "音楽演出", subtitle: "読書を支える音楽のための非表示注釈", hidden: "原稿本文は変更されません", oracle: "オラクルで章を演出", analyzing: "オラクルが読んでいます…", subscription: "美装またはオーディオ購読で利用可能", unavailable: "オラクルはまだ設定されていません", paper: "紙", regions: "領域", noRegions: "音楽領域はまだありません", addRegion: "手動領域を追加", save: "演出を保存", compile: "プロファイルを試す", publish: "体験を公開", saved: "演出を保存しました", compiled: "確認用プロファイルができました", published: "体験を公開しました", accept: "エディターに反映", discard: "破棄", proposal: "オラクルの提案", paragraph: "段落", intensity: "強度", confidence: "確信度", remove: "削除", close: "閉じる", stale: "分析前に章を保存してください", error: "操作を完了できませんでした" },
  zh: { title: "音乐编排", subtitle: "用不可见标注让音乐陪伴阅读", hidden: "不会修改正文", oracle: "用神谕编排本章", analyzing: "神谕正在阅读…", subscription: "美学或音频订阅可用", unavailable: "神谕尚未配置", paper: "纸张", regions: "区域", noRegions: "尚无音乐区域", addRegion: "添加手动区域", save: "保存编排", compile: "测试配置", publish: "发布体验", saved: "编排已保存", compiled: "配置已可供检查", published: "体验已发布", accept: "放入编辑器", discard: "放弃", proposal: "神谕提案", paragraph: "段落", intensity: "强度", confidence: "置信度", remove: "删除", close: "关闭", stale: "请先保存章节再分析", error: "无法完成操作" },
  ar: { title: "الإخراج الموسيقي", subtitle: "ملاحظات خفية لموسيقى ترافق القراءة", hidden: "لا يغيّر نص المخطوطة", oracle: "إخراج الفصل مع أوراكل", analyzing: "أوراكل يقرأ…", subscription: "متاح مع اشتراك الجماليات أو الصوت", unavailable: "لم يُهيّأ أوراكل بعد", paper: "ورق", regions: "مناطق", noRegions: "لا توجد مناطق موسيقية بعد", addRegion: "إضافة منطقة يدوية", save: "حفظ الإخراج", compile: "اختبار الملف", publish: "نشر التجربة", saved: "تم حفظ الإخراج", compiled: "الملف جاهز للمراجعة", published: "تم نشر التجربة", accept: "نقل إلى المحرر", discard: "تجاهل", proposal: "اقتراح أوراكل", paragraph: "الفقرات", intensity: "الشدة", confidence: "الثقة", remove: "حذف", close: "إغلاق", stale: "احفظ الفصل قبل تحليله", error: "تعذر إكمال الإجراء" },
} as const satisfies Record<NarrativeUiLanguage, Record<string, string>>

export type NarrativeUiKey = keyof typeof NARRATIVE_UI_STRINGS.es

export function narrativeUi(language: string) {
  const selected = NARRATIVE_UI_LANGUAGES.includes(language as NarrativeUiLanguage)
    ? language as NarrativeUiLanguage
    : "es"
  return NARRATIVE_UI_STRINGS[selected]
}
