export const SPEECH_UI_LANGUAGES = ["es", "en", "fr", "de", "it", "pt", "ja", "zh", "ar"] as const
export type SpeechUiLanguage = typeof SPEECH_UI_LANGUAGES[number]

const es = {
  title: "Dirección de voz", subtitle: "Voces, actuación y silencios invisibles para el audiolibro", hidden: "No modifica el manuscrito",
  oracle: "Analizar voces con Oráculo", analyzing: "Oráculo está separando las voces…", subscription: "Disponible con suscripción Estética o Audio",
  unavailable: "El análisis con Groq aún no está configurado", stale: "Guarda el capítulo antes de analizarlo", paper: "Papel", narrator: "Narrador",
  characters: "Personajes", fragments: "fragmentos", noFragments: "Todavía no hay dirección de voz", base: "Crear dirección base", addCharacter: "Añadir personaje",
  voice: "Voz", speaker: "Quién habla", delivery: "Interpretación", pauseBefore: "Pausa antes", pauseAfter: "Pausa después", milliseconds: "ms",
  save: "Guardar dirección", compile: "Comprobar audiolibro", publish: "Habilitar para lectores", saved: "Dirección guardada", compiled: "Audiolibro listo para revisar",
  published: "Audiolibro habilitado", accept: "Pasar al editor", discard: "Descartar", proposal: "Propuesta de Oráculo", chooseVoice: "Elige una voz",
  estimated: "Costo estimado", authorReady: "Dirección terminada por el autor", request: "Generar este capítulo", generating: "Preparando audiolibro…",
  cached: "Ya generado · no consume Papel", listen: "Escuchar audiolibro dirigido", audioSubscription: "Disponible con suscripción Audio activa",
  insufficient: "Papel insuficiente", generationOff: "La generación se habilitará al conectar el worker de audio", error: "No se pudo completar la acción",
} as const

type SpeechCopy = Record<keyof typeof es, string>

export const SPEECH_UI_STRINGS = {
  es,
  en: { title: "Voice direction", subtitle: "Invisible voices, delivery and pauses for the audiobook", hidden: "Does not alter the manuscript", oracle: "Analyze voices with Oracle", analyzing: "Oracle is separating voices…", subscription: "Available with Aesthetic or Audio subscription", unavailable: "Groq analysis is not configured yet", stale: "Save the chapter before analyzing it", paper: "Paper", narrator: "Narrator", characters: "Characters", fragments: "segments", noFragments: "No voice direction yet", base: "Create basic direction", addCharacter: "Add character", voice: "Voice", speaker: "Speaker", delivery: "Delivery", pauseBefore: "Pause before", pauseAfter: "Pause after", milliseconds: "ms", save: "Save direction", compile: "Check audiobook", publish: "Enable for readers", saved: "Direction saved", compiled: "Audiobook ready for review", published: "Audiobook enabled", accept: "Move to editor", discard: "Discard", proposal: "Oracle proposal", chooseVoice: "Choose a voice", estimated: "Estimated cost", authorReady: "Direction completed by the author", request: "Generate this chapter", generating: "Preparing audiobook…", cached: "Already generated · uses no Paper", listen: "Listen to directed audiobook", audioSubscription: "Available with an active Audio subscription", insufficient: "Not enough Paper", generationOff: "Generation will be enabled when the audio worker is connected", error: "The action could not be completed" },
  fr: { title: "Direction vocale", subtitle: "Voix, jeu et silences invisibles pour le livre audio", hidden: "Ne modifie pas le manuscrit", oracle: "Analyser les voix avec Oracle", analyzing: "Oracle sépare les voix…", subscription: "Disponible avec l’abonnement Esthétique ou Audio", unavailable: "L’analyse Groq n’est pas encore configurée", stale: "Enregistrez le chapitre avant l’analyse", paper: "Papier", narrator: "Narrateur", characters: "Personnages", fragments: "fragments", noFragments: "Aucune direction vocale", base: "Créer une direction de base", addCharacter: "Ajouter un personnage", voice: "Voix", speaker: "Qui parle", delivery: "Interprétation", pauseBefore: "Pause avant", pauseAfter: "Pause après", milliseconds: "ms", save: "Enregistrer la direction", compile: "Vérifier le livre audio", publish: "Activer pour les lecteurs", saved: "Direction enregistrée", compiled: "Livre audio prêt à vérifier", published: "Livre audio activé", accept: "Passer dans l’éditeur", discard: "Ignorer", proposal: "Proposition d’Oracle", chooseVoice: "Choisir une voix", estimated: "Coût estimé", authorReady: "Direction terminée par l’auteur", request: "Générer ce chapitre", generating: "Préparation du livre audio…", cached: "Déjà généré · aucun Papier consommé", listen: "Écouter le livre audio dirigé", audioSubscription: "Disponible avec un abonnement Audio actif", insufficient: "Papier insuffisant", generationOff: "La génération sera activée après connexion du worker audio", error: "L’action n’a pas pu aboutir" },
  de: { title: "Sprechregie", subtitle: "Unsichtbare Stimmen, Spiel und Pausen für das Hörbuch", hidden: "Ändert das Manuskript nicht", oracle: "Stimmen mit Oracle analysieren", analyzing: "Oracle trennt die Stimmen…", subscription: "Mit Ästhetik- oder Audio-Abo verfügbar", unavailable: "Groq-Analyse ist noch nicht eingerichtet", stale: "Kapitel vor der Analyse speichern", paper: "Papier", narrator: "Erzähler", characters: "Figuren", fragments: "Abschnitte", noFragments: "Noch keine Sprechregie", base: "Grundregie erstellen", addCharacter: "Figur hinzufügen", voice: "Stimme", speaker: "Wer spricht", delivery: "Spielweise", pauseBefore: "Pause davor", pauseAfter: "Pause danach", milliseconds: "ms", save: "Regie speichern", compile: "Hörbuch prüfen", publish: "Für Leser freigeben", saved: "Regie gespeichert", compiled: "Hörbuch bereit zur Prüfung", published: "Hörbuch freigegeben", accept: "In den Editor übernehmen", discard: "Verwerfen", proposal: "Oracle-Vorschlag", chooseVoice: "Stimme wählen", estimated: "Geschätzte Kosten", authorReady: "Regie vom Autor abgeschlossen", request: "Dieses Kapitel erzeugen", generating: "Hörbuch wird vorbereitet…", cached: "Bereits erzeugt · kein Papierverbrauch", listen: "Inszeniertes Hörbuch anhören", audioSubscription: "Mit aktivem Audio-Abo verfügbar", insufficient: "Nicht genug Papier", generationOff: "Die Erzeugung wird nach Anschluss des Audio-Workers aktiviert", error: "Aktion konnte nicht abgeschlossen werden" },
  it: { title: "Direzione vocale", subtitle: "Voci, recitazione e pause invisibili per l’audiolibro", hidden: "Non modifica il manoscritto", oracle: "Analizza le voci con Oracle", analyzing: "Oracle sta separando le voci…", subscription: "Disponibile con abbonamento Estetica o Audio", unavailable: "L’analisi Groq non è ancora configurata", stale: "Salva il capitolo prima dell’analisi", paper: "Carta", narrator: "Narratore", characters: "Personaggi", fragments: "frammenti", noFragments: "Nessuna direzione vocale", base: "Crea direzione di base", addCharacter: "Aggiungi personaggio", voice: "Voce", speaker: "Chi parla", delivery: "Interpretazione", pauseBefore: "Pausa prima", pauseAfter: "Pausa dopo", milliseconds: "ms", save: "Salva direzione", compile: "Controlla audiolibro", publish: "Abilita per i lettori", saved: "Direzione salvata", compiled: "Audiolibro pronto da verificare", published: "Audiolibro abilitato", accept: "Porta nell’editor", discard: "Scarta", proposal: "Proposta di Oracle", chooseVoice: "Scegli una voce", estimated: "Costo stimato", authorReady: "Direzione completata dall’autore", request: "Genera questo capitolo", generating: "Preparazione audiolibro…", cached: "Già generato · non consuma Carta", listen: "Ascolta l’audiolibro diretto", audioSubscription: "Disponibile con abbonamento Audio attivo", insufficient: "Carta insufficiente", generationOff: "La generazione sarà abilitata collegando il worker audio", error: "Impossibile completare l’azione" },
  pt: { title: "Direção de voz", subtitle: "Vozes, interpretação e pausas invisíveis para o audiolivro", hidden: "Não altera o manuscrito", oracle: "Analisar vozes com Oráculo", analyzing: "Oráculo está separando as vozes…", subscription: "Disponível com assinatura Estética ou Áudio", unavailable: "A análise com Groq ainda não está configurada", stale: "Salve o capítulo antes da análise", paper: "Papel", narrator: "Narrador", characters: "Personagens", fragments: "trechos", noFragments: "Ainda não há direção de voz", base: "Criar direção básica", addCharacter: "Adicionar personagem", voice: "Voz", speaker: "Quem fala", delivery: "Interpretação", pauseBefore: "Pausa antes", pauseAfter: "Pausa depois", milliseconds: "ms", save: "Salvar direção", compile: "Verificar audiolivro", publish: "Habilitar para leitores", saved: "Direção salva", compiled: "Audiolivro pronto para revisão", published: "Audiolivro habilitado", accept: "Levar ao editor", discard: "Descartar", proposal: "Proposta do Oráculo", chooseVoice: "Escolha uma voz", estimated: "Custo estimado", authorReady: "Direção concluída pelo autor", request: "Gerar este capítulo", generating: "Preparando audiolivro…", cached: "Já gerado · não consome Papel", listen: "Ouvir audiolivro dirigido", audioSubscription: "Disponível com assinatura Áudio ativa", insufficient: "Papel insuficiente", generationOff: "A geração será habilitada ao conectar o worker de áudio", error: "Não foi possível concluir a ação" },
  ja: { title: "音声演出", subtitle: "オーディオブック用の非表示の声・演技・間", hidden: "原稿本文は変更されません", oracle: "オラクルで声を分析", analyzing: "オラクルが声を分けています…", subscription: "美装またはオーディオ購読で利用可能", unavailable: "Groq 分析はまだ設定されていません", stale: "分析前に章を保存してください", paper: "紙", narrator: "ナレーター", characters: "登場人物", fragments: "区間", noFragments: "音声演出はまだありません", base: "基本演出を作成", addCharacter: "登場人物を追加", voice: "声", speaker: "話者", delivery: "演技", pauseBefore: "前の間", pauseAfter: "後の間", milliseconds: "ミリ秒", save: "演出を保存", compile: "オーディオブックを確認", publish: "読者に公開", saved: "演出を保存しました", compiled: "確認用オーディオブックの準備完了", published: "オーディオブックを公開しました", accept: "エディターに反映", discard: "破棄", proposal: "オラクルの提案", chooseVoice: "声を選ぶ", estimated: "推定コスト", authorReady: "作者による演出が完了", request: "この章を生成", generating: "オーディオブックを準備中…", cached: "生成済み・紙を消費しません", listen: "演出付きオーディオブックを聴く", audioSubscription: "有効なオーディオ購読で利用可能", insufficient: "紙が足りません", generationOff: "音声ワーカー接続後に生成が有効になります", error: "操作を完了できませんでした" },
  zh: { title: "语音编排", subtitle: "用于有声书的隐形声音、表演和停顿标注", hidden: "不会修改正文", oracle: "用神谕分析声音", analyzing: "神谕正在区分声音…", subscription: "美学或音频订阅可用", unavailable: "Groq 分析尚未配置", stale: "请先保存章节再分析", paper: "纸张", narrator: "旁白", characters: "角色", fragments: "片段", noFragments: "尚无语音编排", base: "创建基础编排", addCharacter: "添加角色", voice: "声音", speaker: "说话者", delivery: "演绎", pauseBefore: "前置停顿", pauseAfter: "后置停顿", milliseconds: "毫秒", save: "保存编排", compile: "检查有声书", publish: "向读者开放", saved: "编排已保存", compiled: "有声书已可供检查", published: "有声书已开放", accept: "放入编辑器", discard: "放弃", proposal: "神谕提案", chooseVoice: "选择声音", estimated: "预计成本", authorReady: "作者已完成编排", request: "生成本章", generating: "正在准备有声书…", cached: "已生成 · 不消耗纸张", listen: "收听编排版有声书", audioSubscription: "有效音频订阅可用", insufficient: "纸张不足", generationOff: "连接音频工作进程后将启用生成", error: "无法完成操作" },
  ar: { title: "الإخراج الصوتي", subtitle: "أصوات وأداء وصمت خفي للكتاب الصوتي", hidden: "لا يغيّر نص المخطوطة", oracle: "تحليل الأصوات مع أوراكل", analyzing: "أوراكل يفصل الأصوات…", subscription: "متاح مع اشتراك الجماليات أو الصوت", unavailable: "لم يُهيّأ تحليل Groq بعد", stale: "احفظ الفصل قبل تحليله", paper: "ورق", narrator: "الراوي", characters: "الشخصيات", fragments: "مقاطع", noFragments: "لا يوجد إخراج صوتي بعد", base: "إنشاء إخراج أساسي", addCharacter: "إضافة شخصية", voice: "الصوت", speaker: "المتحدث", delivery: "الأداء", pauseBefore: "صمت قبل", pauseAfter: "صمت بعد", milliseconds: "مللي ثانية", save: "حفظ الإخراج", compile: "فحص الكتاب الصوتي", publish: "إتاحته للقراء", saved: "تم حفظ الإخراج", compiled: "الكتاب الصوتي جاهز للمراجعة", published: "تمت إتاحة الكتاب الصوتي", accept: "نقل إلى المحرر", discard: "تجاهل", proposal: "اقتراح أوراكل", chooseVoice: "اختر صوتاً", estimated: "التكلفة المقدّرة", authorReady: "أكمل المؤلف الإخراج", request: "إنشاء هذا الفصل", generating: "يجري إعداد الكتاب الصوتي…", cached: "مُنشأ مسبقاً · لا يستهلك ورقاً", listen: "الاستماع إلى الكتاب الصوتي المُخرج", audioSubscription: "متاح مع اشتراك صوت نشط", insufficient: "الورق غير كافٍ", generationOff: "سيُفعّل الإنشاء بعد توصيل عامل الصوت", error: "تعذر إكمال الإجراء" },
} as const satisfies Record<SpeechUiLanguage, SpeechCopy>

export type SpeechUiKey = keyof typeof es

export function speechUi(language: string): SpeechCopy {
  const selected = SPEECH_UI_LANGUAGES.includes(language as SpeechUiLanguage) ? language as SpeechUiLanguage : "es"
  return SPEECH_UI_STRINGS[selected]
}
