import type { AppLanguage } from "@/context/SettingsContext"

const es = {
  explore: "Explorar los clásicos", lead: "Encuentra tu próxima lectura entre las ediciones de Project Gutenberg.",
  search: "Título, autor, número o enlace de Gutenberg", language: "Idioma de la edición", all: "Todos los idiomas",
  topic: "Tema", sort: "Orden", popular: "Más leídos", descending: "Incorporaciones recientes", ascending: "Primeras incorporaciones",
  topics: ["Todos los temas", "Ficción", "Aventura", "Misterio", "Fantasía", "Poesía", "Filosofía", "Literatura infantil"],
  results: "{n} ediciones en la fuente", page: "Página", previous: "Anterior", next: "Siguiente", retry: "Reintentar",
  error: "No pudimos conectar con Gutenberg. Puedes volver a intentarlo.", empty: "No hay ediciones con estos filtros.",
  tryAll: "Buscar en todos los idiomas", back: "Volver a resultados", choose: "Una biblioteca por descubrir",
  chooseHint: "Abre una edición para recorrer sus capítulos y leer una muestra antes de guardarla.",
  sample: "Leer una muestra", sourceSummary: "Resumen de la fuente", metadataSummary: "Ficha bibliográfica",
  original: "El texto y el resumen se conservan en su idioma de origen. El filtro no traduce la obra.",
  minutes: "min de lectura aprox.", words: "palabras aprox.", full: "Texto íntegro. No se identificaron capítulos con suficiente claridad.",
  detected: "División automática. Revisa el índice y las páginas iniciales antes de publicar.",
  publish: "Publicar en catálogo", draft: "Guardar borrador", importAs: "Destino de la importación", draftSaved: "Borrador guardado",
  existing: "Ver edición importada", loading: "Preparando la edición…", translators: "Traducción", ready: "Edición lista para revisar",
  sampleHint: "Muestra del capítulo; la copia guardada incluye el texto completo.",
}
type Copy = { [K in keyof typeof es]: typeof es[K] }
const en: Copy = {
  explore: "Explore the classics", lead: "Find your next read among Project Gutenberg editions.",
  search: "Title, author, Gutenberg number or link", language: "Edition language", all: "All languages", topic: "Topic", sort: "Sort",
  popular: "Most read", descending: "Recently added", ascending: "Earliest additions", topics: ["All topics", "Fiction", "Adventure", "Mystery", "Fantasy", "Poetry", "Philosophy", "Children’s literature"],
  results: "{n} editions at the source", page: "Page", previous: "Previous", next: "Next", retry: "Retry", error: "We could not connect to Gutenberg. Please try again.",
  empty: "No editions match these filters.", tryAll: "Search all languages", back: "Back to results", choose: "A library to discover",
  chooseHint: "Open an edition to explore its chapters and read a sample before saving it.", sample: "Read a sample", sourceSummary: "Source summary", metadataSummary: "Bibliographic record",
  original: "Text and summary retain their source language. The filter does not translate the book.", minutes: "min estimated reading", words: "approx. words",
  full: "Full text. Chapters could not be identified reliably.", detected: "Automatic chapter detection. Review the contents and opening pages before publishing.",
  publish: "Publish to catalog", draft: "Save draft", importAs: "Import destination", draftSaved: "Draft saved", existing: "View imported edition",
  loading: "Preparing the edition…", translators: "Translation", ready: "Edition ready for review", sampleHint: "Chapter sample; the saved copy includes the full text.",
}
const copies: Record<AppLanguage, Copy> = {
  es, en,
  fr: {
    explore: "Explorer les classiques", lead: "Trouvez votre prochaine lecture parmi les éditions de Project Gutenberg.", search: "Titre, auteur, numéro ou lien Gutenberg", language: "Langue de l’édition", all: "Toutes les langues", topic: "Thème", sort: "Ordre", popular: "Les plus lus", descending: "Ajouts récents", ascending: "Premiers ajouts", topics: ["Tous les thèmes", "Fiction", "Aventure", "Mystère", "Fantasy", "Poésie", "Philosophie", "Littérature jeunesse"], results: "{n} éditions à la source", page: "Page", previous: "Précédente", next: "Suivante", retry: "Réessayer", error: "Connexion à Gutenberg impossible. Réessayez.", empty: "Aucune édition avec ces filtres.", tryAll: "Chercher dans toutes les langues", back: "Retour aux résultats", choose: "Une bibliothèque à découvrir", chooseHint: "Ouvrez une édition pour parcourir les chapitres et lire un extrait avant de l’enregistrer.", sample: "Lire un extrait", sourceSummary: "Résumé de la source", metadataSummary: "Notice bibliographique", original: "Le texte et le résumé conservent leur langue d’origine. Le filtre ne traduit pas l’œuvre.", minutes: "min de lecture estimée", words: "mots environ", full: "Texte intégral. Les chapitres n’ont pas pu être identifiés avec certitude.", detected: "Découpage automatique. Vérifiez le sommaire et les premières pages avant publication.", publish: "Publier au catalogue", draft: "Enregistrer un brouillon", importAs: "Destination de l’import", draftSaved: "Brouillon enregistré", existing: "Voir l’édition importée", loading: "Préparation de l’édition…", translators: "Traduction", ready: "Édition prête à vérifier", sampleHint: "Extrait du chapitre ; la copie enregistrée contient le texte intégral.",
  },
  de: {
    explore: "Klassiker entdecken", lead: "Finde deine nächste Lektüre unter den Ausgaben von Project Gutenberg.", search: "Titel, Autor, Gutenberg-Nummer oder Link", language: "Sprache der Ausgabe", all: "Alle Sprachen", topic: "Thema", sort: "Sortierung", popular: "Meistgelesen", descending: "Neu hinzugefügt", ascending: "Früheste Einträge", topics: ["Alle Themen", "Belletristik", "Abenteuer", "Krimi", "Fantasy", "Lyrik", "Philosophie", "Kinderliteratur"], results: "{n} Ausgaben an der Quelle", page: "Seite", previous: "Zurück", next: "Weiter", retry: "Erneut versuchen", error: "Keine Verbindung zu Gutenberg. Bitte erneut versuchen.", empty: "Keine Ausgaben mit diesen Filtern.", tryAll: "In allen Sprachen suchen", back: "Zurück zu Ergebnissen", choose: "Eine Bibliothek entdecken", chooseHint: "Öffne eine Ausgabe, um Kapitel und eine Leseprobe vor dem Speichern anzusehen.", sample: "Leseprobe", sourceSummary: "Zusammenfassung der Quelle", metadataSummary: "Bibliografische Angaben", original: "Text und Zusammenfassung bleiben in ihrer Quellsprache. Der Filter übersetzt das Werk nicht.", minutes: "Min. geschätzte Lesezeit", words: "Wörter ungefähr", full: "Volltext. Kapitel konnten nicht zuverlässig erkannt werden.", detected: "Automatische Kapitel. Prüfe Inhaltsverzeichnis und Anfangsseiten vor dem Veröffentlichen.", publish: "Im Katalog veröffentlichen", draft: "Entwurf speichern", importAs: "Importziel", draftSaved: "Entwurf gespeichert", existing: "Importierte Ausgabe öffnen", loading: "Ausgabe wird vorbereitet…", translators: "Übersetzung", ready: "Ausgabe zur Prüfung bereit", sampleHint: "Kapitelauszug; die gespeicherte Kopie enthält den Volltext.",
  },
  it: {
    explore: "Esplora i classici", lead: "Trova la tua prossima lettura tra le edizioni di Project Gutenberg.", search: "Titolo, autore, numero o link Gutenberg", language: "Lingua dell’edizione", all: "Tutte le lingue", topic: "Tema", sort: "Ordine", popular: "Più letti", descending: "Aggiunte recenti", ascending: "Prime aggiunte", topics: ["Tutti i temi", "Narrativa", "Avventura", "Mistero", "Fantasy", "Poesia", "Filosofia", "Letteratura per ragazzi"], results: "{n} edizioni alla fonte", page: "Pagina", previous: "Precedente", next: "Successiva", retry: "Riprova", error: "Impossibile connettersi a Gutenberg. Riprova.", empty: "Nessuna edizione con questi filtri.", tryAll: "Cerca in tutte le lingue", back: "Torna ai risultati", choose: "Una biblioteca da scoprire", chooseHint: "Apri un’edizione per sfogliare i capitoli e leggere un estratto prima di salvarla.", sample: "Leggi un estratto", sourceSummary: "Riassunto della fonte", metadataSummary: "Scheda bibliografica", original: "Testo e riassunto mantengono la lingua di origine. Il filtro non traduce l’opera.", minutes: "min di lettura stimati", words: "parole circa", full: "Testo integrale. Non è stato possibile identificare i capitoli con certezza.", detected: "Suddivisione automatica. Controlla indice e pagine iniziali prima di pubblicare.", publish: "Pubblica nel catalogo", draft: "Salva bozza", importAs: "Destinazione importazione", draftSaved: "Bozza salvata", existing: "Vedi edizione importata", loading: "Preparazione dell’edizione…", translators: "Traduzione", ready: "Edizione pronta per la revisione", sampleHint: "Estratto del capitolo; la copia salvata include il testo integrale.",
  },
  pt: {
    explore: "Explorar os clássicos", lead: "Encontra a tua próxima leitura nas edições do Project Gutenberg.", search: "Título, autor, número ou ligação Gutenberg", language: "Idioma da edição", all: "Todos os idiomas", topic: "Tema", sort: "Ordem", popular: "Mais lidos", descending: "Adições recentes", ascending: "Primeiras adições", topics: ["Todos os temas", "Ficção", "Aventura", "Mistério", "Fantasia", "Poesia", "Filosofia", "Literatura infantil"], results: "{n} edições na fonte", page: "Página", previous: "Anterior", next: "Seguinte", retry: "Tentar novamente", error: "Não foi possível ligar ao Gutenberg. Tenta novamente.", empty: "Nenhuma edição com estes filtros.", tryAll: "Pesquisar em todos os idiomas", back: "Voltar aos resultados", choose: "Uma biblioteca por descobrir", chooseHint: "Abre uma edição para explorar os capítulos e ler uma amostra antes de a guardar.", sample: "Ler uma amostra", sourceSummary: "Resumo da fonte", metadataSummary: "Ficha bibliográfica", original: "O texto e o resumo mantêm o idioma de origem. O filtro não traduz a obra.", minutes: "min de leitura estimada", words: "palavras aprox.", full: "Texto integral. Não foi possível identificar os capítulos com segurança.", detected: "Divisão automática. Revê o índice e as páginas iniciais antes de publicar.", publish: "Publicar no catálogo", draft: "Guardar rascunho", importAs: "Destino da importação", draftSaved: "Rascunho guardado", existing: "Ver edição importada", loading: "A preparar a edição…", translators: "Tradução", ready: "Edição pronta para revisão", sampleHint: "Amostra do capítulo; a cópia guardada inclui o texto integral.",
  },
  ja: {
    explore: "古典を探す", lead: "Project Gutenbergの作品から次の一冊を見つけましょう。", search: "題名、著者、Gutenberg番号またはリンク", language: "版の言語", all: "すべての言語", topic: "テーマ", sort: "並び順", popular: "人気順", descending: "追加が新しい順", ascending: "追加が古い順", topics: ["すべてのテーマ", "小説", "冒険", "ミステリー", "ファンタジー", "詩", "哲学", "児童文学"], results: "出典に{n}件の版", page: "ページ", previous: "前へ", next: "次へ", retry: "再試行", error: "Gutenbergに接続できません。再試行してください。", empty: "この条件に一致する版はありません。", tryAll: "すべての言語で検索", back: "結果に戻る", choose: "発見を待つ図書館", chooseHint: "版を開き、章や試し読みを確認してから保存できます。", sample: "試し読み", sourceSummary: "出典の要約", metadataSummary: "書誌情報", original: "本文と要約は出典の言語のままです。絞り込みによる翻訳は行いません。", minutes: "分・読書時間の目安", words: "語程度", full: "全文。章を確実に識別できませんでした。", detected: "章は自動で分割されています。公開前に目次と冒頭を確認してください。", publish: "カタログに公開", draft: "下書きを保存", importAs: "取り込み先", draftSaved: "下書きを保存しました", existing: "取り込み済みの版を見る", loading: "版を準備中…", translators: "翻訳", ready: "版を確認できます", sampleHint: "章の一部を表示しています。保存したコピーには全文が含まれます。",
  },
  zh: {
    explore: "探索经典", lead: "在 Project Gutenberg 的版本中寻找下一本好书。", search: "书名、作者、Gutenberg 编号或链接", language: "版本语言", all: "所有语言", topic: "主题", sort: "排序", popular: "热门阅读", descending: "最近收录", ascending: "最早收录", topics: ["全部主题", "小说", "冒险", "悬疑", "奇幻", "诗歌", "哲学", "儿童文学"], results: "来源中有 {n} 个版本", page: "页", previous: "上一页", next: "下一页", retry: "重试", error: "无法连接 Gutenberg，请重试。", empty: "没有符合这些条件的版本。", tryAll: "搜索所有语言", back: "返回结果", choose: "等待探索的书库", chooseHint: "打开版本，浏览章节并试读后再保存。", sample: "试读", sourceSummary: "来源摘要", metadataSummary: "书目信息", original: "正文和摘要保留来源语言。筛选不会翻译作品。", minutes: "分钟，预计阅读时间", words: "字词，约", full: "完整正文。未能可靠地识别章节。", detected: "章节自动划分。发布前请检查目录和开篇。", publish: "发布到目录", draft: "保存草稿", importAs: "导入目标", draftSaved: "草稿已保存", existing: "查看已导入版本", loading: "正在准备版本…", translators: "翻译", ready: "版本已准备好，可供审阅", sampleHint: "仅显示章节片段；保存的副本包含完整正文。",
  },
  ar: {
    explore: "استكشف الكلاسيكيات", lead: "اعثر على قراءتك القادمة بين إصدارات Project Gutenberg.", search: "العنوان أو المؤلف أو رقم Gutenberg أو رابطه", language: "لغة الإصدار", all: "جميع اللغات", topic: "الموضوع", sort: "الترتيب", popular: "الأكثر قراءة", descending: "الأحدث إضافة", ascending: "الأقدم إضافة", topics: ["جميع المواضيع", "الخيال", "المغامرة", "الغموض", "الفانتازيا", "الشعر", "الفلسفة", "أدب الأطفال"], results: "{n} إصدار في المصدر", page: "صفحة", previous: "السابق", next: "التالي", retry: "إعادة المحاولة", error: "تعذر الاتصال بـ Gutenberg. أعد المحاولة.", empty: "لا توجد إصدارات تطابق هذه المرشحات.", tryAll: "البحث بجميع اللغات", back: "العودة إلى النتائج", choose: "مكتبة تنتظر الاكتشاف", chooseHint: "افتح إصدارًا لاستعراض فصوله وقراءة مقتطف قبل حفظه.", sample: "قراءة مقتطف", sourceSummary: "ملخص المصدر", metadataSummary: "بيانات ببليوغرافية", original: "يبقى النص والملخص بلغة المصدر. المرشح لا يترجم العمل.", minutes: "دقيقة قراءة تقريبًا", words: "كلمة تقريبًا", full: "النص الكامل. تعذر تحديد الفصول بدقة كافية.", detected: "تقسيم تلقائي. راجع الفهرس والصفحات الأولى قبل النشر.", publish: "النشر في الفهرس", draft: "حفظ مسودة", importAs: "وجهة الاستيراد", draftSaved: "تم حفظ المسودة", existing: "عرض الإصدار المستورد", loading: "جارٍ تجهيز الإصدار…", translators: "الترجمة", ready: "الإصدار جاهز للمراجعة", sampleHint: "مقتطف من الفصل؛ النسخة المحفوظة تتضمن النص الكامل.",
  },
}
export const gutenbergCopy = (language: AppLanguage) => copies[language] || es
